"""add health_risk_scores table

Revision ID: 691dffcd3bdc
Revises: 8e68e75135a3
Create Date: 2026-07-17 14:44:46.621372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '691dffcd3bdc'
down_revision: Union[str, None] = '8e68e75135a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_risk_scores_patient_id'), 'health_risk_scores', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_risk_scores_patient_id'), table_name='health_risk_scores')
    op.drop_table('health_risk_scores')
    # ### end Alembic commands ###
