"""create doctors and related tables

Revision ID: 69477f4e2e06
Revises: 2ed058f53cc3
Create Date: 2026-07-15 05:38:00.576408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69477f4e2e06'
down_revision: Union[str, None] = '2ed058f53cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=True)
    op.create_table('doctor_patient_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patient_assignments_doctor_id'), 'doctor_patient_assignments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_assignments_patient_id'), 'doctor_patient_assignments', ['patient_id'], unique=False)
    op.create_table('patient_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_notes_doctor_id'), 'patient_notes', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_notes_patient_id'), 'patient_notes', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_notes_patient_id'), table_name='patient_notes')
    op.drop_index(op.f('ix_patient_notes_doctor_id'), table_name='patient_notes')
    op.drop_table('patient_notes')
    op.drop_index(op.f('ix_doctor_patient_assignments_patient_id'), table_name='doctor_patient_assignments')
    op.drop_index(op.f('ix_doctor_patient_assignments_doctor_id'), table_name='doctor_patient_assignments')
    op.drop_table('doctor_patient_assignments')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
